<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        //class error manual
        class ValidationError extends Error{
            constructor(message, field) {
                super(message);
                this.field = field;
            }
        }
        class MathUtil {
            static sum (... numbers){

                if (numbers.length === 0){
                    throw new ValidationError ('Total parameter harus lebih dari 0', 'numbers')//menambahkan informasi
                }
                let total = 0;
                for (const number of numbers) {
                    total += number;
                }
                return total;
            }
        } 

        try {
            //trigger error
            console.info(MathUtil.sum());
            console.info('eko');
        }
        //kalo di blok try tidak error maka blok catch tidak di jalankan
        catch(error){
            //update catch
            if(error instanceof ValidationError){
                console.error(`Terjadi Error di: ${error.message} -Terjadi Error Field  di: ${error.field}`);
            }
            else{
                console.info(`Terjadi error : error ${error.message}`);
            }
        }
        //error ga error tetep jalan
        finally{
            console.info('program selesai');
        }
        console.info('ucup');
    </script>
</body>
</html>